name: CeltiClan
main: fr.pitiqui.celticlan.Main
version: 0.1.8B
description: Gestion de clan pour CeltiCraft !
author: pitiqui
commands:
  clan:
    description: Commande principale du plugin !