name: CeltiClan
main: fr.pitiqui.celticlan.Main
version: 0.1.3
description: Gestion de clan pour CeltiCraft !
author: pitiqui
database: true
commands:
  clan:
    description: Commande principale du plugin !